Documentation
NordicMRspine/MRINavigator.jl pull request #49
Opened 2024-02-28 08:36 UTC by Laura2305

- Update documentation (on Siemens data concatenation = 1 is required).
- Add test data link.

2024-04-19 17:29 UTC, alexjaffray requested changes
Remove the test/.DS_Store file, otherwise approved!

2024-04-19 17:29 UTC, alexjaffray commented on test/.DS_Store
Is this supposed to be here? I think it's a hidden file that made it's way in.

2024-04-21 19:51 UTC, Laura2305 commented on test/.DS_Store
@alexjaffray it's a hidden file used by Mac finder. There's no reason for it to be in the GitHub folder.

2024-04-23 13:58 UTC, alexjaffray approved these changes

2024-04-23 14:40 UTC, merged